#!/bin/bash

read -p "Enter version type (major, minor or patch [default: patch]): " version_type
if [ -z "$version_type" ]; then
  version_type="patch"
fi

current_version=$(cat Cargo.toml | grep -Po '(?<=version = ")[^"]*')

case $version_type in 
  major)
    new_version=$(echo $current_version | awk 'BEGIN{FS="."}{print ++$1 ".0.0"}')
    ;;
  minor)
    new_version=$(echo $current_version | awk 'BEGIN{FS="."}{print $1 "." ++$2 ".0"}')
    ;;
  patch)
    new_version=$(echo $current_version | awk 'BEGIN{FS="."}{print $1 "." $2 "." ++$3}')
esac

if [ -z "$new_version" ]; then
    echo "Could not generate a new version"
    exit 1
fi

sed -i "s/version = "$current_version"/version = "$new_version"/g" Cargo.toml
sed -i "s/$current_version/$new_version/g" readme.md
cargo build
git add Cargo.toml Cargo.lock readme.md && git commit -m"build: release new version $new_version" && git tag $new_version

echo "Updated from $current_version to $new_version successfully"